[theme]
base="light"
primaryColor="#000000"
backgroundColor="#8fbc8b"
secondaryBackgroundColor="#12582f"
textColor="#272424"
[theme]
base="dark"
primaryColor="#000000"
backgroundColor="#8fbc8b"
secondaryBackgroundColor="#12582f"
textColor="#272424"